Repository fastmachinelearning/hls4ml, pull requests merged in 2022-11, with the labels that each got.

#481 skip BatchNorm fusion when input/output is used multiple times
  hls4ml/backends/fpga/passes/clone.py
  hls4ml/model/layers.py
  hls4ml/model/optimizer/passes/bn_fuse.py
  hls4ml/model/optimizer/passes/qkeras.py
Labels: bug

#678 Adiabatically turn on `pre-commit`
  .clang-format
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  MANIFEST.in
  setup.cfg
Labels: enhancement, please test

#688 Add causal padding
  hls4ml/backends/vivado/passes/conv_same_pad.py
  hls4ml/converters/utils.py
  test/pytest/test_causalpadding.py
Labels: please test
