Repository fastmachinelearning/hls4ml, pull requests merged in 2023-04, with the labels that each got.

#751 fix Vitis pragmas messed up by pre-commit
  hls4ml/templates/vitis/nnet_utils/nnet_pooling.h
Labels: bug, please test

#750 Additional cleanup of the codebase
  contrib/garnet.py
  hls4ml/backends/quartus/passes/merge_templates.py
  hls4ml/backends/vivado/passes/merge_templates.py
  hls4ml/converters/__init__.py
  hls4ml/converters/keras/core.py
  hls4ml/converters/keras/qkeras.py
  hls4ml/converters/keras/qkeras_layers.py
  hls4ml/converters/keras_to_hls.py
  hls4ml/converters/utils.py
  hls4ml/model/layers.py
  hls4ml/model/optimizer/__init__.py
  hls4ml/model/optimizer/passes/qkeras.py
  hls4ml/model/types.py
  hls4ml/utils/config.py
  hls4ml/writer/quartus_writer.py
  hls4ml/writer/vivado_writer.py
Labels: please test

#754 Fix for BatchNormalization layers with `center=False` or `scale=False`
  hls4ml/converters/keras/core.py
  hls4ml/converters/pytorch/core.py
  hls4ml/model/layers.py
  test/pytest/test_batchnorm.py
Labels: bug

#757 Fix pooling layers when padding is applied from the left/top
  docs/requirements.txt
  hls4ml/templates/quartus/firmware/nnet_utils/nnet_pooling.h
  hls4ml/templates/vitis/nnet_utils/nnet_pooling.h
  hls4ml/templates/vivado/nnet_utils/nnet_pooling.h
  test/pytest/test_pooling.py
Labels: please test

#744 Further update documentation for 0.7.0
  CITATION.cff
  README.md
  docs/advanced/accelerator.rst
  docs/conf.py
  docs/flows.rst
  docs/img/pynqframe.png
  docs/img/zynq_interfaces.png
  docs/index.rst
  docs/reference.rst
  docs/setup.rst
Labels: please test

#772 add a default weight_size
  hls4ml/writer/quartus_writer.py
Labels: bug

#749 CNNs with binary inputs and weights need fixes
  hls4ml/backends/fpga/passes/bn_quant.py
  hls4ml/templates/quartus/firmware/nnet_utils/nnet_batchnorm.h
  hls4ml/templates/quartus/firmware/nnet_utils/nnet_batchnorm_stream.h
  hls4ml/templates/quartus/firmware/nnet_utils/nnet_mult.h
  hls4ml/templates/vivado/nnet_utils/nnet_batchnorm.h
  hls4ml/templates/vivado/nnet_utils/nnet_batchnorm_stream.h
  hls4ml/templates/vivado/nnet_utils/nnet_conv1d_latency.h
  hls4ml/templates/vivado/nnet_utils/nnet_conv2d_latency.h
  hls4ml/templates/vivado/nnet_utils/nnet_sepconv_stream.h
  test/pytest/test_binary_cnn.py
Labels: bug, please test
