Repository fastmachinelearning/hls4ml, pull requests merged in 2024-11, with the labels that each got.

#1112 Make auto default precision for pytorch parser
  hls4ml/utils/config.py
Labels: please test

#1130 remove incorrect setting of result_t
  hls4ml/model/optimizer/passes/linear.py
  hls4ml/model/optimizer/passes/merge_const.py
  hls4ml/model/optimizer/passes/quant_opt.py
Labels: bug

#1132 Fix problem with scale being a multidimensional array.
  hls4ml/model/optimizer/passes/quant_opt.py
Labels: bug, please test

#1136 Update install_requires for 1.0.0
  setup.cfg
Labels: please test
